// Viewer Commands
module.exports = [
    {name: "!congratulations", response: "wlvs.info/congrats_"},
    {name: "!Geno", response: "Geno pls"},
    {name: "!link", response: "no, you can't post a link"},
    {name: "!subsong", response: "The sub song is a custom mix made for Jay by his friend Chris https://twitter.com/ChrisMelee"},
    {name: "!wes", response: "U WES A, U WES A"},
    {name: "!pungence", response: "youtube.com/c/pungence twitch.tv/pungence"},
    {name: "!yes", response: "http://wlvs.info/yes_"},
    {name: "!kevin", response: "watch the light dude"},
    {name: "!ThirdParty", response: "Click inventory -> Trade Offers -> Who can send me Trade Offers? -> your third party trade link will be at the bottom of the page."},
    {name: "!guild", response: "Looking for the Wolfpack Guild on Steam? Look no further: wlvs.info/wlvs_pack"},
    {name: "!hooch", response: "Hooch IS crazy."},
    {name: "!outrosong", response: "Lorde - Tennis Court (Flume Remix) https://www.youtube.com/watch?v, response: 8ATu1BiOPZA"},
    {name: "!even", response: "wlvs.info/even_"},
    {name: "!schedule", response: "Jay will be streaming on Monday, Wednesday, Thursday, and Saturday! Follow Twitter for more exact times! twitter.com/wlvsatmydoor"},
    {name: "!peaks", response: "Λʌʍ^W^ʍʌΛ"},
    {name: "!surf", response: "Want to learn how to surf as great as Jay? Here is a super helpful 5 minute video that goes over everything from the basics to advanced techniques:       wlvs.info/surf_help"},
    {name: "!group", response: "Looking for the Wolfpack on Steam? Look no further: wlvs.info/wlvs_pack"},
    {name: "!rap", response: "Come check out Jay's lyrical prowess... wlvs.info/hook_club"},
    {name: "!trade", response: "The link for a direct trade to Jason is: wlvs.info/wolf_trade"},
    {name: "!maps", response: "Head on over to: wlvs.info/map_pack to download and install maps for the arena server."},
    {name: "!follow", response: "Enjoying the stream? Make sure you catch all the action by hitting the FOLLOW button below the video. You'll get a notification every time Jason goes live."},
    {name: "!hud", response: "The H.U.D. color for CS:GO can be changed in the game settings as of the 5.1.2014 patch."},
    {name: "!knife", response: "Yes, Jay is a beast. Yes, he has gotten TWELVE knives out of cases, because he is a beast. wlvs.info/knife_openings The luck is real boys!"},
    {name: "!social", response: "Don't forget to check Jason out on YouTube https://youtube.com/thewolvesatmydoor and Twitter https://twitter.com/wlvsatmydoor and Instagram http://instagram.com/wolvesatmydoor"},
    {name: "!donate", response: "We're just happy you're here, but if you'd really like to donate to Jason, head to streamtip.com/t/wolvesatmydoor Donations aren't necessary, but for those of you who feel the need, it is greatly appreciated. Seriously."},
    {name: "!subscribe", response: "If you're enjoying the stream and would like to support Jason, consider subscribing by clicking the button below the video or going to: twitch.tv/wolvesatmydoor/subscribe"},
    {name: "!sub", response: "If you're enjoying the stream and would like to support Jason, consider subscribing by clicking the button below the video or going to: twitch.tv/wolvesatmydoor/subscribe"},
    {name: "!metro", response: "For info about Jay's steam skin head to: http://www.metroforsteam.com"},
    {name: "!ask", response: "Have a random question for Jason? You can ask it right here: http://ask.fm/jasonthenicest"},
    {name: "!site", response: "Come check out the site! wolvesatmydoor.com"},
    {name: "!web", response: "Come check out the site! wolvesatmydoor.com"},
    {name: "!playlist", response: "Check out all of Jay's public Spotify Playlists HERE: https://open.spotify.com/user/jasonthenicest"},
    {name: "!spotify", response: "CS playlist: wlvs.info/cs_playlist Binding of Isaac playlist: wlvs.info/isaac_playlist"},
    {name: "!neverforget", response: "wlvs.info/NEVER_F0RGET"},
    {name: "!background", response: "wlvs.info/partofthepack"},    
    {name: "!steam", response: "For info about Jay's steam skin head to: http://www.metroforsteam.com"},
    {name: "!wopo", response: "╭∩╮（︶︿︶）╭∩╮"},
    {name: "!milky", response: "Mooooooo."},
    {name: "!pls", response: "Please do not tell Jay how to play the game unless he asks. No spoilers!"},
    {name: "!gta5crew", response: "Join the Wolfpack crew on GTA5! wlvs.info/gta_crew"},
    {name: "!applause", response: "wlvs.info/_applause_"},
    {name: "!itemtracker", response: "The bar at the bottom of the screen is an item tracker! You can find more information about it here: https://github.com/Hyphen-ated/RebirthItemTracker/releases"},
    {name: "!snapchat", response: "jasonthenicest"},
    {name: "!wasteland", response: "If Jay had a terrorist of his own... wlvs.info/wasteland_"},
    {name: "!donationsong", response: "The donation song is a custom mix made for Jay by his friend Chris. The melody is sampled from: Timmy Trumpet & Savage - Freaks."},
    {name: "!isaac", response: "#spoilers wlvs.info/isaac_story"},
    {name: "!wink", response: "wlvs.info/wink_"},
    {name: "!4thwall", response: "wlvs.info/4th_wall"},
    {name: "!trevsSecret", response: "https://www.youtube.com/watch?v", response: "tLogeQfPQGk"},
    {name: "!krissy", response: "u wot m8"},
    {name: "!5000", response: "Jay won a $5000+ pot in CSGOshuffle, that's how he got the Dragonlore, Karambit Doppler, etc... wlvs.info/5000_"},
    {name: "!hair", response: "wlvs.info/princess_hair"},
    {name: "!astro", response: "Jay has been sponsored by Astro! If you are considering buying some Astro gear feel free to do so here! wlvs.info/_astro"},
    {name: "!trev", response: "<3"},
    {name: "!tattoos", response: "Click here to see jay's tattoos explained: wlvs.info/_tattoos_"},
    {name: "!emotes", response: "https://twitchemotes.com/channels/41721716"},
    {name: "!nick", response: "F I R S T S U B E V A R wolvesWat"},
    {name: "!les", response: "http://gyazo.com/99f94a861f5cc7971c6bd652e2b02c2b"},
    {name: "!bttv", response: "To get extra emotes as well as the gif emotes download BTTV here http://www.nightdev.com/betterttv/"},
    {name: "!kate", response: "Jay's way better half. Good at the video games. Amazing person. Excellent streamer. http://www.twitch.tv/kateedge https://twitter.com/kateedge7"},
    {name: "!tj", response: "https://gyazo.com/c39e50ba1cd1f5aed58df14598f890ee"},
    {name: "!headshot", response: "http://i.imgur.com/GRvwvI9.gifv"},
    {name: "!highschool", response: "http://puu.sh/bdkFF/b604bf1b49.jpg"},
    {name: "!nickgee", response: "wolvesWat"},
    {name: "!subdrawing", response: "wlvs.info/sub_pics"},
    {name: "!lights", response: "Jay has Phillips Hue lights. You can find more information about them here: http://www2.meethue.com/en-us/"},
    {name: "!j8", response: "https://www.youtube.com/watch?v", response: "wsZ7013yHiw"},
    {name: "!topd", response: "The top donation song is a mix of this video: https://www.youtube.com/watch?vwsZ7013yHiw and the song Senses by Prismo."},
    {name: "!setup", response: "https://www.youtube.com/watch?v", response: "ATl8NcVTmV8"},
    {name: "!vlog", response: "The long awaited... much anticipated... (slightly disappointing) Room Tour and Set-Up VLOG! wlvs.info/room_tour"},
    {name: "!cozy", response: "Jay, Dough, Wes, and a friend made a skit. It's 10/10. Check it outtttt. https://youtu.be/VY485inw2V8"},
    {name: "!lit", response: "wlvs.info/lit_"},
    {name: "!age", response: "wlvs.info/_old_"},
    {name: "!flip", response: "wolvesThrow ︵ ┻━┻"},
    {name: "!facepaint", response: "wolvesKappa Nice face paint, it matches your vagina nicely! wolvesKappa"},
    {name: "!bdubs", response: "You probably know him already. If not, he does the stream thing now, not the YouTube thing. Better looking than Jay too. https://twitter.com/BdoubleO100 https://www.twitch.tv/bdoubleo"},
    {name: "!chair", response: "Hi, I'm chair. I run this show wolvesKappa"},
    {name: "!waldough", response: "Waldough is not here, he probably quit."},
    {name: "!dab", response: "wlvs.info/dab_ wolvesDab"},
    {name: "!merch", response: "Looking to pick up the latest Jay merch? Head over to: wlvs.info/merch_warehouse"},
    {name: "!videosatmydoor", response: "Each playlist will become public after the videos have been watched on stream. You can watch previous playlists here: wlvs.info/wolfpackbot_yt"},
    {name: "!wolvesSneeze", response: "wolvesThrow wolvesDab"},
    {name: "!litfam", response: "Sickest of memes. twitter.com/shauntpetro"},
    {name: "!raid", response: "We the wolfpack and in a real-life situation Squirtle would never win in a fight against some of the more powerful Pokemon like Charzander and even Peekatyou because Squirtle is just a little turtle and he's not fit for this world, he must evolve to be fighting other pokemons."},
    {name: "!mc", response: "wlvs.info/sub_pics"},
    {name: "!LoresOutTheDoors", response: "https://www.twitch.tv/wolvesatmydoor/v/59870392"},
    {name: "!keyboard", response: "Corsair K70 RGB wlvs.info/corsair_"},
    {name: "!minecraft", response: "Survival of the Quittest. Society of Quitters."},
    {name: "!hanzo", response: "wlvs.info/hanzo_art"},
    {name: "!youtube", response: "Check out the youtube channel for more video games such as Isaac, Madden, Planet Coaster and more! https://youtube.com/thewolvesatmydoor"},
    {name: "!nintendo", response: "Nintendo ID : wlvsatmydoor"},
    {name: "!discord", response: "New subs, directions to join discord: wlvs.info/_discord"},
    {name: "!destram", response: "Josh collects dead people."},
    {name: "!alerts", response: "Jay and Mike (decoydix) do the alerts and popups. Commissions are open at wlvs.tv"},
    {name: "!bits", response: "This channel now accepts bits; please check out wlvs.info/bits_ for more info on cheering. Thanks for the support wolvesSub"},
    {name: "!playlists", response: "Check out all of Jay's public Spotify Playlists HERE: https://open.spotify.com/user/jasonthenicest"},
    {name: "!twitter", response: "twitter.com/wlvsatmydoor"},
    {name: "!antibirth", response: "Antibirth is a mod for Isaac that adds a bunch of new items, rooms, and 2 new playable characters. Antibirth.com"},
    {name: "!bsn", response: "PogChamp PogChamp PogChamp PogChamp PogChamp"},
    {name: "!void", response: "When used with a passive item on a pedestal -> two stat changes, when used with an active item on a pedestal -> becomes one with the void (triggers both void and other spacebar item)"},
    {name: "!isaacmod", response: "wlvs.info/wolves_character"},
    {name: "!notification", response: "Make sure you get notified everytime I go live! https://gyazo.com/a777e8f31aac7bb26f906a84101b02c4"},
    {name: "!pobox", response: "wolvesatmydoor | P.O. Box 55 | Matawan, NJ 07747"},
    {name: "!currentmod", response: "TwitchToIsaac https://vfstudio.github.io/IsaacOnTwitch/"},
    {name: "!oni", response: "Oxygen Not Included is a space-colony simulation game. Manage your colonists and help them dig, build and maintain a subterranean asteroid base."},
    {name: "!hp", response: "in the 'Bit Boss minigame' Jay starts as the Boss. Donating bits will chip away the health bar. Score the killing blow and become the new Boss of the stream."},
    {name: "!bitboss", response: "in the 'Bit Boss minigame' Jay starts as the Boss. Donating bits will chip away the health bar. Score the killing blow and become the new Boss of the stream."},
    {name: "!avatar", response: "Yeah the blue people that speak the different language. Oh there is that one Goku fucking anime Avatar isn’t there. The last air-breather or something. All like the oxygen in the world gets taken out and that guy is the last guy who can breathe air. He has like an arrow on his head, pointing to his mouth where he breathes in the air. Yeah that shit… is lit."},
    {name: "!naruto", response: "He’s mixing up Nare-a-two with You-go? I don’t know. They’re all the one-punch man in different outfits. Don’t lie to me dude. They’re all just the one-punch-man dressed up in different colors.. Everybody's super saying at the end of the day. If one guys saying something, the other ones super saying it. And then their hair lights up, that’s just the end of, that’s just what happens."},
    {name: "!wave", response: "Jay's sub notifications are remixed by his friend Chris! Check out https://twitter.com/theWAVECUTTERS for more beats!"},
    {name: "!waldo", response: "Check out Jay's friend Waldo! Weekly vlogs, skits, funny guy. https://twitter.com/Wall_Dough http://bit.ly/2sdKLGv (YouTube Channel)"},
    {name: "!seed", response: "-2043652089"},
    {name: "!popvinyls", response: "wlvs.info/pop_vinyls"},
    {name: "!hats", response: "WLVS Drip Dad Hats -> http://bit.ly/2jciZKq"},
    {name: "!subavatars", response: "wlvs.info/sub_avatars"},
    {name: "!pop", response: "Here is Jay's POP Vinyl collection: wlvs.info/pop_vinyls"},
    {name: "!destiny", response: "wlvs.info/wolfpackworldwide"},
    {name: "!fulltime", response: "Jay is currently pursuing a full-time Twitch schedule. He will be live 6 days a week (taking Sundays off). YouTube will be on a bit of a hiatus for the time being."},
    {name: "!newsub", response: "have you been a viewer of jay's for a while now but couldn't bring youself to spend 4.99$ on the clown? you're in luck! you can now sub for half off any brand new sub valid until october 2nd!"},
    {name: "!hats", response: "WLVS Drip Dad Hats -> http://bit.ly/2jciZKq"},
    {name: "!sweatpants", response: "WLVS sweats are coming! Need to know your size? http://www.jerzees.com/975MPR.shtml?menu", response: " Click that link, and look at the specs! Need to know how many of each size? 6-Small 7-Medium 7-Large 4-XL 3-XXL 2-XXXL. Once they gone, they gone!"},
    {name: "!october", response: "imgur.com/a/la9dl"},
    {name: "!no", response: "https://clips.twitch.tv/ShortSteamySnailKeepo"},
    {name: "!windbreaker", response: "Grab the WLVS Box hoodie or windbreaker before it's gone Nov 11! https://streamerswarehouse.com/collections/wolvesatmydoor"},
    {name: "!cheesenips", response: "https://www.youtube.com/watch?v", response: "DWLf_CVf8Nc"},
    {name: "!forivy", response: "Todays stream is dedicated to @BdoubleO and family; please do not donate through my tip link or bits. Use the gofundme here to support: https://www.gofundme.com/forivy2018. There is also a shirt available for a limited time at https://teespring.com/forivy all proceeds will goto bdubs and family. Thank you here is bdubs video for context; http://bit.ly/2CfN2dq"},
    {name: "!gofundme", response: "http://www.gofundme.com/forivy2018"},
    {name: "!shirt", response: "https://teespring.com/forivy"},
    {name: "!gofundme", response: "http://www.gofundme.com/forivy2018"},
    {name: "!multi", response: "http://kadgar.net/live/wolvesatmydoor/kateedge"},
    {name: "!variety", response: "I’m Wolvesatmydoor , and this is my variety stream. I live here with my girlfriend, KateEdge. Everygame in here has uniqueness and individuality. One thing I’ve learned after 4 years of variety streaming – you always know that FORTNITE will eventually be played. (iamspuds)"},
    {name: "!pizza", response: "https://clips.twitch.tv/ManlyEagerKumquatSaltBae"},
    {name: "!LoA", response: "If youre gonna buy Legends of Aria use my link! http://www.legendsofaria.com/purchase/?referral"},
]



